#!/bin/bash
gcc -S -masm=intel $CFILE
#include <stdio.h>
#include <unistd.h>

/**
* main - Entry point
*
* Return
*/
int main(void)
{
	write(2,"and that piece of art is useful\" - Dora Korpar, 2015-10-19\n", 59);
	return (1);
}

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- INSERT --                                                                                                                                                                  2,1      
